from tau2.utils.utils import DATA_DIR

FOOD_DELIVERY_APP_DATA_DIR = DATA_DIR / "tau2" / "domains" / "food_delivery_app"
FOOD_DELIVERY_APP_DB_PATH = FOOD_DELIVERY_APP_DATA_DIR / "db.json"
FOOD_DELIVERY_APP_POLICY_PATH = FOOD_DELIVERY_APP_DATA_DIR / "policy.md"
FOOD_DELIVERY_APP_TASK_SET_PATH = FOOD_DELIVERY_APP_DATA_DIR / "tasks.json"
FOOD_DELIVERY_APP_TASK_SET_SOLO_PATH = FOOD_DELIVERY_APP_DATA_DIR / "tasks_solo.json"
